weather_app/weather/urls.py
from django.conf.urls import url
from . import views
from .views import autocompleteModel

app_name = 'weather'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^stored_data/$', views.stored_data, name='stored_data'),
    url(r'^ajax_calls/search/', autocompleteModel, name='search'),
]

weather_app/weather_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls')),
]

weather_app/weather/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField


class City(models.Model):
    name = models.CharField(max_length=50)
    created = models.DateField(auto_now_add=True)
    data = JSONField(default=dict)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name: 'City'
        verbose_name_plural: 'Cities'

weather_app/weather/forms.py
from .models import City
from django.forms.widgets import SelectDateWidget, TextInput
from django import forms


class CityForm(forms.ModelForm):

    class Meta:
        model = City
        fields = ['name']
        widgets = {
            'name': TextInput(
                attrs={'type': 'text', 'id': 'txtSearch', 'class': 'input', 'placeholder': 'City Name', }),
        }


class SearchForm(forms.ModelForm):

    date_from = forms.DateField(widget=SelectDateWidget(years=range(2000, 2025), months={
        1: ('1'), 2: ('2'), 3: ('3'), 4: ('4'),
        5: ('5'), 6: ('6'), 7: ('7'), 8: ('8'),
        9: ('9'), 10: ('10'), 11: ('11'), 12: ('12')
    }), required=False)
    date_to = forms.DateField(widget=SelectDateWidget(years=range(2000, 2025), months={
        1: ('1'), 2: ('2'), 3: ('3'), 4: ('4'),
        5: ('5'), 6: ('6'), 7: ('7'), 8: ('8'),
        9: ('9'), 10: ('10'), 11: ('11'), 12: ('12')
    }), required=False)

    name = forms.CharField(required=False)

    class Meta:
        model = City

        fields = ['name', 'date_from', 'date_to']

weather_app/weather/views.py
import requests
from django.shortcuts import render
from .models import City
from .forms import CityForm, SearchForm
from django_tables2 import RequestConfig
from .tables import CityTable
import json
from django.http import HttpResponse


def index(request):
    url = 'http://api.openweathermap.org/data/2.5/weather?q={}&units=metric&appid=831404ac4314d3d14d7afbe6b6265d92'

    if request.method == 'POST':
        form = CityForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
    name = request.POST.get('name')
    form = CityForm()

    city = City()
    city.data = requests.get(url.format(name)).json()

    if city.data['cod'] == '404':
        city.name = name
        print(city.name)
    elif city.data['name'] == 'None':
        print(city.data['name'])
        pass
    else:
        city.name = city.data['name']
        city.save()

    context = {'form': form, 'city': city}
    return render(request, 'weather/search.html', context)


def stored_data(request):
    form_city_filter = SearchForm()

    table = CityTable(City.objects.all())

    if request.method == 'POST':
        form_city_filter = SearchForm(request.POST)
        if form_city_filter.is_valid():
            date_from = form_city_filter.cleaned_data.get('date_from')
            date_to = form_city_filter.cleaned_data.get('date_to')
            form_city_filter.save(commit=False)
    cname = request.POST.get('name')

    if cname and date_to == None and date_from == None:
        table = CityTable(City.objects.raw('SELECT * FROM weather_city WHERE name = %s', [cname]))
    elif cname == '' and date_from and date_to:
        table = CityTable(
            City.objects.raw('SELECT * FROM weather_city WHERE created BETWEEN %s AND %s', [date_from, date_to]))
    elif cname and date_from and date_to:
        table = CityTable(City.objects.raw('SELECT * FROM weather_city WHERE name = %s AND created BETWEEN %s AND %s  ',
                                           [cname, date_from, date_to]))
    else:
        pass

    RequestConfig(request, paginate={'per_page': 5}).configure(table)

    context = {'table': table, 'form_city_filter': form_city_filter}
    return render(request, 'weather/base.html', context)


def autocompleteModel(request):
    if request.is_ajax():
        q = request.GET.get('term', '').capitalize()
        search_qs = City.objects.filter(name__startswith=q)
        results = []
        for r in search_qs:
            results.append(r.name)
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

weather_app/weather/templates/weather/base.html
<!DOCTYPE html>
    {% load render_table from django_tables2 %}
    {% load django_tables2 %}
    {% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
</head>
<body>
<form action="{% url 'weather:stored_data' %}">
    <input type="submit" value="Base" />
</form>

    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    <form method="POST" novalidate>
                        {% csrf_token %}
                        <div class="">
                             <div class="">
                                 {{ form_city_filter.name }}
                                 {{ form_city_filter.date_from}}
                                 {{ form_city_filter.date_to }}
                            </div>
                            <div class="">
                                <button type="submit">
                                    Search
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% block table-wrapper %}
<div class="table-container">
    {% block table %}
        <table {% render_attrs table.attrs class="table" %}>
            {% block table.thead %}
            {% if table.show_header %}
                <thead {{ table.attrs.thead.as_html }}>
                    <tr>
                    {% for column in table.columns %}
                        <th {{ column.attrs.th.as_html }}>
                            {% if column.orderable %}
                                <a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header }}</a>
                            {% else %}
                                {{ column.header }}
                            {% endif %}
                        </th>
                    {% endfor %}
                    </tr>
                </thead>
            {% endif %}
            {% endblock table.thead %}
            {% block table.tbody %}
                <tbody {{ table.attrs.tbody.as_html }}>
                {% for row in table.paginated_rows %}
                    {% block table.tbody.row %}
                    <tr {{ row.attrs.as_html }}>
                        {% for column, cell in row.items %}
                            <td {{ column.attrs.td.as_html }}>{% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}</td>
                        {% endfor %}
                    </tr>
                    {% endblock table.tbody.row %}
                {% empty %}
                    {% if table.empty_text %}
                    {% block table.tbody.empty_text %}
                        <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
                    {% endblock table.tbody.empty_text %}
                    {% endif %}
                {% endfor %}
                </tbody>
            {% endblock table.tbody %}
            {% block table.tfoot %}
            {% if table.has_footer %}
                <tfoot {{ table.attrs.tfoot.as_html }}>
                    <tr>
                    {% for column in table.columns %}
                        <td {{ column.attrs.tf.as_html }}>{{ column.footer }}</td>
                    {% endfor %}
                    </tr>
                </tfoot>
            {% endif %}
            {% endblock table.tfoot %}
        </table>
    {% endblock table %}

    {% block pagination %}
        {% if table.page and table.paginator.num_pages > 1 %}
        <nav aria-label="Table navigation">
            <ul class="pagination">
            {% if table.page.has_previous %}
                {% block pagination.previous %}
                    <li class="previous">
                        <a href="{% querystring table.prefixed_page_field=table.page.previous_page_number %}">
                            <span aria-hidden="true">&laquo;</span>
                            {% trans 'previous' %}
                        </a>
                    </li>
                {% endblock pagination.previous %}
            {% endif %}
            {% if table.page.has_previous or table.page.has_next %}
                {% block pagination.range %}
                    {% for p in table.page|table_page_range:table.paginator %}
                        <li {% if p == table.page.number %}class="active"{% endif %}>
                            {% if p == '...' %}
                                <a href="#">{{ p }}</a>
                            {% else %}
                                <a href="{% querystring table.prefixed_page_field=p %}">
                                    {{ p }}
                                </a>
                            {% endif %}
                        </li>
                    {% endfor %}
                {% endblock pagination.range %}
            {% endif %}

            {% if table.page.has_next %}
                {% block pagination.next %}
                <li class="next">
                    <a href="{% querystring table.prefixed_page_field=table.page.next_page_number %}">
                        {% trans 'next' %}
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endblock pagination.next %}
            {% endif %}
            </ul>
        </nav>
        {% endif %}
    {% endblock pagination %}
</div>
{% endblock table-wrapper %}
</body>
</html>

weather_app/weather/templates/weather/search.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>

    <script>
        $(document).ready(function(){
            $("#txtSearch").autocomplete({
                source: "/ajax_calls/search/",
                minLength: 2,
                open: function(){
                    setTimeout(function () {
                        $('.ui-autocomplete').css('z-index', 99);
                    }, 0);
                }
              });
        });
</script>

</head>

<body>
    <section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    What's the weather like?
                </h1>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    <form id=”search” method="POST" action="{% url 'weather:index' %}">
                        {% csrf_token %}
                        <div class="field has-addons">
                             <div class="control is-expanded">

                                   {{form.name}}

                             </div>
                            <div class="control">
                                 <button type="submit" class="button is-info">Search</button>
                            </div>
                        </div>
                    </form>
                    <form action="{% url 'weather:stored_data' %}">
                          <input type="submit" value="Base" />
                    </form>
                </div>
            </div>
        </div>
    </section>

    {%  if city.data.cod == 200 and city.data.name != 'None'%}
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    <div class="box">
                        <article class="media">
                            <div class="media-left">
                                <figure class="image is-50x50">
                                    <img src="http://openweathermap.org/img/w/{{ city.data.weather.0.icon }}.png" alt="Image">
                                </figure>
                            </div>
                            <div class="media-content">
                                <div class="content">
                                    <p>
                                        <span class="title">{{ city.name }}</span>
                                        <br>
                                        <span class="subtitle">{{city.data.main.temp}}° C</span>
                                        <br> {{ city.data.weather.0.description }}
                                    </p>
                                </div>
                            </div>
                        </article>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% elif city.data.name == 'None' %}
        <section class="section">
            <div class="container">
                <div class="columns">
                    <div class="column is-offset-4 is-4">
                        <div class="box">
                           <h4>Hello. Enter the city name.</h4>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    {% else %}
        <section class="section">
            <div class="container">
                <div class="columns">
                    <div class="column is-offset-4 is-4">
                        <div class="box">
                           <h4>Wrong input. Please try again.</h4>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    {% endif %}
</body>

</html>